Cmdb/Cmdb/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from dashboard.views import Index,getresult,Login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/',include("dashboard.urls")),
    path('user/',include("user.urls")),
    path('resources/',include("resources.urls")),
    re_path('^$', Index.as_view()),
    path('getresult/', getresult),
    path('login/', Login.as_view()),

]

Cmdb/resources/models.py
from django.db import models
from user.models import Company

HOST_STATUS = (
    (0, 'Unknown'),
    (1, 'up'),
    (2, 'down'),

)
SCAN_STATUS = (
    (0, '待探测'),
    (1, '正在探测'),
    (2, '探测成功'),
    (3, '探测失败')
)


## 主机
class Host(models.Model):
    """
    ip 资产信息
    """
    ip = models.CharField(max_length=32, verbose_name="主机ip")
    status = models.IntegerField(choices=HOST_STATUS, default=1, verbose_name="主机状态")
    scan_status = models.IntegerField(choices=SCAN_STATUS, default=0, verbose_name="主机探测状态")
    company = models.ForeignKey(to=Company, on_delete=models.CASCADE)


## 主机用户
class HostUser(models.Model):
    """
    主机用户
    """
    username = models.CharField(max_length=32, verbose_name="用户名")
    password = models.CharField(max_length=32, verbose_name="登陆密码")
    host = models.ForeignKey(to=Host, on_delete=models.CASCADE)  ### 用户名和主机为一对多关系


#
class TasksOrder(models.Model):
    """
    扫描任务
    """
    order_no = models.CharField(max_length=36, verbose_name="订单号")
    create_time = models.DateTimeField(auto_now=True, verbose_name="创建时间")
    # host = models.ForeignKey(to=Host,on_delete=models.CASCADE)
    celeryinfoid = models.IntegerField(verbose_name="CeleryInfo表的id", default=0)


class CeleryInfo(models.Model):
    task_id = models.TextField(verbose_name="celery任务id")
    time = models.DateTimeField(auto_now=True)

IMAGE_STATUS= (
    (0,'未确定'),
    (1,'高危'),
    (2,'安全')
)
class OrderInfo(models.Model):
    """
    扫描详情
    """
    order = models.ForeignKey(to=TasksOrder, on_delete=models.CASCADE)
    host = models.ForeignKey(to=Host, on_delete=models.CASCADE)
    # celeryinfo = models.ForeignKey(to=CeleryInfo, on_delete=models.CASCADE)
    port = models.IntegerField(verbose_name="扫描开发的端口号", null=True)
    image = models.CharField(max_length=256, null=True, verbose_name="截图之后图片路径")
    simple_image = models.CharField(max_length=256, null=True, verbose_name="相似图片路径")
    percent = models.FloatField(default=0,verbose_name="相似概率")
    status = models.IntegerField(default=0,verbose_name="图片状态")
class OpenPort(models.Model):
    host = models.ForeignKey(to=Host, on_delete=models.CASCADE)
    task_order = models.ForeignKey(to=TasksOrder, on_delete=models.CASCADE)
    port = models.CharField(max_length=32, verbose_name="端口")
    state = models.CharField(max_length=32, verbose_name="状态")
    reason = models.TextField(verbose_name="原因")
    extrainfo = models.TextField(verbose_name="额外信息")
    name = models.TextField(verbose_name="名字")
    version = models.TextField(verbose_name="版本")
    product = models.TextField(verbose_name="产品")
    cpe = models.TextField(verbose_name="CPE")
    script = models.TextField(verbose_name="脚本")

Cmdb/resources/templates/Idclist.html
{% extends 'base.html' %}
{% block style %}
    <link href="/static/css/sweetalert/sweetalert.css" rel="stylesheet">

{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>机房展示 </h5>
            </div>
            <div class="ibox-content">
                <a class="btn btn-w-m btn-primary" href="{% url 'addidc' %}">创建机房</a>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">机房简称</th>
                        <th class="text-center">机房名称</th>
                        <th class="text-center">机房地址</th>
                        <th class="text-center">机房电话</th>
                        <th class="text-center">机房联系人姓名</th>
                        <th class="text-center">机房联系人邮箱</th>
                        <th class="text-center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td class="text-center">{{ object.idc_name }}</td>
                            <td class="text-center">{{ object.idc_name_all }}</td>
                            <td class="text-center">{{ object.address }}</td>
                            <td class="text-center">{{ object.phone }}</td>
                            <td class="text-center">{{ object.name }}</td>
                            <td class="text-center">{{ object.email }}</td>
                            <td class="text-center">
                                <a href="{% url 'idc_update' %}?id={{ object.id }}"
                                   class="btn btn-primary btn-sm">更新</a>
                                <a class="btn btn-danger btn-sm" onclick="idc_delete({{ object.id }})">删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>

    <ul style="float: right;margin-right: 50px;" class="pagination">
        {% if page_obj.has_previous %}
            <a class='page-link' href="{% url "idc" %}?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        {% for page in page_range %}
            <li class="paginate_button page-item">

                <a class='page-link' href="{% url "idc" %}?page={{ page }}">{{ page }}</a>

            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <a class='page-link' href="{% url "idc" %}?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}

    </ul>

{% endblock %}


{% block script %}
    <script src="/static/js/sweetalert/sweetalert.min.js"></script>
    <script>
        function idc_delete(id) {
            var data = {};
            data['id'] = id;
            data['csrfmiddlewaretoken'] = "{{ csrf_token }}";
            $.ajax({
                url: '{% url 'idc_delete' %}',
                type: 'post',
                data: data,
                success: function (res) {
                    if (res.code == 10000) {
                        console.log(res)
                        swal({
                            title: res.msg,
                            type: 'success',
                            confirmButtonText: "OK"
                        }, function () {
                            window.location.reload()
                        });
                    } else {
                        swal({
                            title: res.msg,
                            type: 'error',
                            confirmButtonText: "知道了"
                        });
                    }
                }
            })
        };
    </script>
{% endblock %}

Cmdb/resources/templates/addIdc.html
{% extends "base.html" %}
{% block title %}
    增加机房
{% endblock %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">增加机房</h6>
        </div>
        <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="idc_name" placeholder="机房简称" class="form-control form-control-user">
                </div>
                <div class="form-group">
                    <input type="text" name="idc_name_all" placeholder="机房全称" class="form-control form-control-user">
                </div>
                <div class="form-group">
                    <input type="text" name="address" placeholder="机房地址" class="form-control form-control-user">
                </div>
                <div class="form-group">
                    <input type="text" name="phone" placeholder="机房电话" class="form-control form-control-user">
                </div>
                <div class="form-group">
                    <input type="text" name="name" placeholder="机房联系人姓名" class="form-control form-control-user">
                </div>
                <div class="form-group">
                    <input type="text" name="email" placeholder="邮箱" class="form-control form-control-user">
                </div>


                <div class="form-group">
                    <input type="submit" value="增加机房" class="btn btn-primary btn-user btn-block">
                </div>

            </form>


        </div>
    </div>


{% endblock %}

Cmdb/resources/templates/addhost.html
{% extends "base.html" %}
{% block title %}
    录入资产
{% endblock %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">录入资产</h6>
        </div>
        <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="ip" placeholder="Ip地址" class="form-control form-control-user">
                </div>
                <div class="form-group">
                    <select class="form-control" name="company">
                        <option>--选择单位--</option>
                        {% for one in com_obj %}
                            <option value="{{ one.id }}">{{ one.company }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <input type="text" name="username" placeholder="登陆账号" class="form-control form-control-user">
                </div>
                <div class="form-group">
                    <input type="password" name="password" placeholder="登陆密码" class="form-control form-control-user">
                </div>

                <div class="form-group form-check">
                    <input type="checkbox" class="form-check-input" name="checked" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">选择主机探测(探测主机是否存活)</label>
                </div>

                <div class="form-group">
                    <input type="submit" value="增加机房" class="btn btn-primary btn-user btn-block">
                </div>

            </form>


        </div>
    </div>


{% endblock %}

Cmdb/resources/templates/createtasks.html
{% extends "base.html" %}
{% block style %}
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/js/sweetalert/sweetalert.min.js"></script>
    <link href="/static/css/sweetalert/sweetalert.css" rel="stylesheet">

{% endblock %}

{% block content %}
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">创建检测任务</h6>
    </div>
    <form action="" method="post">
        {% csrf_token %}

        <table class="table table-striped">
            <thead>
            <tr>
                <th>
                    <input type="checkbox" id="all_box"> 全选
                </th>
                <th>IP</th>

            </tr>
            </thead>
            <tbody>

            {% for object in object_list %}
                <tr>
                    <th scope="row"><input type="checkbox" class="onecheck" name="{{ object.id }}"></th>
                    <td>
                        {{ object.ip }}
                    </td>
                </tr>

            {% endfor %}
            <tr>
                <td colspan='2'>
                    <input type="button" value="开始任务" class="btn btn-primary btn-user btn-block" id="createtask">
                </td>
            </tr>

            </tbody>
        </table>
    </form>


{% endblock %}

{% block script %}


    <script>

        $(".onecheck").each(
            function () {
                $(this).click(
                    function () {
                        if (!this.checked) {
                            // True
                            $("#all_box").prop("checked", false)
                        }
                    }
                )
            }
        )


        $("#all_box").click(
            function () {
                // 点击全选，将所有的全部选中   checked
                //console.log(this.checked);   //  判断当前的元素对象是否有checked 属性
                //  如果为 True 有checked属性   被选中的状态
                if (this.checked) {
                    //   True
                    // 被选中   设置 每一项 增加checked 属性
                    // 通过类选择器 找到元素  增加checked 属性
                    $(".onecheck").prop("checked", true);

                } else {
                    // 去掉所有元素的 checked 属性
                    $(".onecheck").prop("checked", false);
                }

            }
        )

        $("#createtask").click(
            function () {
                {#console.log(111)#}
                // 获取被选中的选项
                var data = [];
                $(".onecheck").each(
                    function () {
                        if (this.checked) {
                            var c_id = this.name
                            {#console.log(c_id)#}
                            data.push(c_id)
                        }
                    }
                )
                {#console.log(data)#}
                var send_data = {
                    "data": data,
                    "csrfmiddlewaretoken": "{{ csrf_token }}"

                };

                $.ajax({
                    url: "{% url "create_task" %}",
                    type: "post",
                    data: send_data,
                    success: function (res) {
                        if (res.code == 10000) {
                            console.log(res)
                            swal({
                                title: res.msg,
                                type: 'success',
                                confirmButtonText: "OK"
                            }, function () {
                                window.location.reload()
                            });
                        } else {
                            swal({
                                title: res.msg,
                                type: 'error',
                                confirmButtonText: "知道了"
                            });
                        }
                    }


                })

            }
        )


    </script>




{% endblock %}

Cmdb/resources/templates/host_info.html
{% extends "base.html" %}



{% block content %}
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">资产详细信息</h6>
    </div>

    <table class="table table-bordered">
        <tr>
            <th>IP</th>
            <td>{{ host_object.ip }}</td>
            <th>机房</th>
            <td>{{ host_object.idc.name }}</td>
            <th>机房全称</th>
            <td>{{ host_object.idc.idc_name_all }}</td>
        </tr>
        <tr>
            <th>主机状态</th>
            <td>{{ host_object.get_status_display }}</td>
            <th>主机探测状态</th>
            <td>{{ host_object.get_scan_status_display }}</td>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th>账号</th>
            <td colspan="4">
                {% for user in host_object.hostuser_set.all %}
                    {{ user.username }}
                {% endfor %}
            </td>

        </tr>


    </table>



{% endblock %}

Cmdb/resources/templates/host_list.html
{% extends 'base.html' %}
{% block style %}
    <link href="/static/css/sweetalert/sweetalert.css" rel="stylesheet">

{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>资产信息展示</h5>
            </div>
            <div class="ibox-content">
                <a class="btn btn-w-m btn-primary" href="{% url 'host_add' %}">录入资产</a>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">主机ip</th>
                        <th class="text-center">所属单位</th>
                        <th class="text-center">用户名</th>
                        <th class="text-center">状态</th>

                        <th class="text-center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td class="text-center">{{ object.ip }}</td>
                            <td class="text-center">{{ object.company.company }}</td>
                            <td class="text-center">{{ object.hostuser_set.first.username }}
                                {#                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"#}
                                {#                                        data-target=".bd-example-modal-sm">增加账号#}
                                {#                                </button>#}
                                {##}
                                {#                                <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog"#}
                                {#                                     aria-labelledby="mySmallModalLabel" aria-hidden="true">#}
                                {#                                    <div class="modal-dialog modal-sm" role="document">#}
                                {#                                        <div class="modal-content">#}
                                {#                                            <div class="modal-body">#}
                                {#                                                <form>#}
                                {#                                                    <div class="form-group">#}
                                {#                                                        <label for="recipient-name"#}
                                {#                                                               class="col-form-label">账号:</label>#}
                                {#                                                        <input type="text" name="username" class="form-control"#}
                                {#                                                               id="recipient-name">#}
                                {#                                                    </div>#}
                                {#                                                    <div class="form-group">#}
                                {#                                                        <label for="message-text"#}
                                {#                                                               class="col-form-label">密码:</label>#}
                                {#                                                        <input type="password" name="password" class="form-control"#}
                                {#                                                               id="message-text">#}
                                {#                                                    </div>#}
                                {#                                                    <input type="hidden" name="id" value="{{ object.id }}">#}
                                {##}
                                {#                                                    <button type="button" class="btn btn-secondary"#}
                                {#                                                            data-dismiss="modal">Close#}
                                {#                                                    </button>#}
                                {#                                                    <input type="submit" class="btn btn-primary" value="保存">#}
                                {#                                                </form>#}
                                {#                                            </div>#}
                                {#                                        </div>#}
                                {#                                    </div>#}
                                {#                                </div>#}
                            </td>


                            <td class="text-center">{{ object.get_status_display }}</td>


                            {#                            <td class="text-center">#}
                            {#                                <a href="{% url 'idc_update' %}?id={{ object.id }}"#}
                            {#                                   class="btn btn-primary btn-sm">更新</a>#}
                            {#                                <a class="btn btn-danger btn-sm" onclick="idc_delete({{ object.id }})">删除</a>#}
                            {#                            </td>#}
                            <td class="text-center">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-primary dropdown-toggle btn-sm" href="#"
                                            role="button"
                                            id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                                            aria-expanded="false">
                                        操作
                                    </button>

                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        {#                                        <a class="badge badge-primary dropdown-item"#}
                                        {#                                           href="{% url 'idc_update' %}?id={{ object.id }}">更新</a>#}
                                        {#                                        <a class="badge badge-primary dropdown-item"#}
                                        {#                                           href="{% url 'idc_update' %}?id={{ object.id }}">增加登陆用户</a>#}
                                        {#                                        <a class="badge badge-info dropdown-item"#}
                                        {#                                           href="{% url 'idc_update' %}?id={{ object.id }}">查看更多信息</a>#}
                                        {#                                        <a class="badge badge-danger dropdown-item"#}
                                        {#                                           href="{% url 'idc_update' %}?id={{ object.id }}">删除</a>#}

                                        {#                                        <a class="dropdown-item badge badge-primary" onclick="idc_delete({{ object.id }})">删除</a>#}

                                        {#                                        <a class="dropdown-item" href="#">Something else here</a>#}
                                        <a class="dropdown-item"
                                           href="{% url 'host_info' %}?id={{ object.id }}">查看更多</a>
                                        <a class="dropdown-item"
                                           href="{% url 'host_update' %}?id={{ object.id }}">修改</a>
                                        <a class="dropdown-item"
                                           onclick="tance({{ object.id }})">主机探测</a>



                                        <!-- Small modal -->

                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item"
                                           onclick="host_delete({{ object.id }})">删除</a>


                                        {#                                        <a class="dropdown-item" href="#">Something else here</a>#}


                                    </div>
                                </div>
                            </td>
                        </tr>

                    {% endfor %}


                    </tbody>
                </table>

            </div>
        </div>
    </div>

    <ul style="float: right;margin-right: 50px;" class="pagination">
        {% if page_obj.has_previous %}
            <a class='page-link' href="{% url "host_list" %}?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        {% for page in page_range %}
            <li class="paginate_button page-item">

                <a class='page-link' href="{% url "host_list" %}?page={{ page }}">{{ page }}</a>

            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <a class='page-link' href="{% url "host_list" %}?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}

    </ul>

{% endblock %}


{% block script %}
    <script src="/static/js/sweetalert/sweetalert.min.js"></script>
    <script>
     function tance(id) {
            var data = {};
            data['id'] = id;
            data['csrfmiddlewaretoken'] = "{{ csrf_token }}";
            $.ajax({
                url: '{% url 'tancehost' %}',
                type: 'post',
                data: data,
                success: function (res) {
                    if (res.code == 10000) {
                        console.log(res)
                        swal({
                            title: res.msg,
                            type: 'success',
                            confirmButtonText: "OK"
                        }, function () {
                            window.location.reload()
                        });
                    } else {
                        swal({
                            title: res.msg,
                            type: 'error',
                            confirmButtonText: "知道了"
                        });
                    }
                }
            })
        };


        function host_delete(id) {
            var data = {};
            data['id'] = id;
            data['csrfmiddlewaretoken'] = "{{ csrf_token }}";
            $.ajax({
                url: '{% url 'host_delete' %}',
                type: 'post',
                data: data,
                success: function (res) {
                    if (res.code == 10000) {
                        console.log(res)
                        swal({
                            title: res.msg,
                            type: 'success',
                            confirmButtonText: "OK"
                        }, function () {
                            window.location.reload()
                        });
                    } else {
                        swal({
                            title: res.msg,
                            type: 'error',
                            confirmButtonText: "知道了"
                        });
                    }
                }
            })
        };
    </script>
{% endblock %}

Cmdb/resources/templates/update_host.html
{% extends "base.html" %}
{% block content %}


    <form>
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">主机信息</h6>
        </div>

        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">IP地址</label>
            <div class="col-sm-2">
                <input type="text" readonly class="form-control-plaintext" value="{{ host_obj.ip }}">
            </div>
            <label for="staticEmail" class="col-sm-2 col-form-label">状态</label>
            <div class="col-sm-2">
                <input type="text" readonly class="form-control-plaintext" value="{{ host_obj.get_status_display }}">
            </div>
            <label for="staticEmail" class="col-sm-2 col-form-label">探测状态</label>
            <div class="col-sm-2">
                <input type="text" readonly class="form-control-plaintext"
                       value="{{ host_obj.get_scan_status_display }}">
            </div>

        </div>

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">单位信息</h6>
        </div>


        <div class="form-group row">

            <label for="staticEmail" class="col-sm-2 col-form-label">单位名称</label>
            <div class="col-sm-2">
                <input type="text" class="form-control-plaintext" readonly value="{{ host_obj.company.company }}">
            </div>
{##}
{#            <label for="staticEmail" class="col-sm-2 col-form-label">机房全称</label>#}
{#            <div class="col-sm-2">#}
{#                <input type="text" class="form-control-plaintext" readonly value="{{ host_obj.idc.idc_name_all }}">#}
{#            </div>#}
            <label for="staticEmail" class="col-sm-2 col-form-label">单位地址</label>
            <div class="col-sm-2">
                <input type="text" class="form-control-plaintext" readonly value="{{ host_obj.company.address }}">
            </div>

        </div>

        <div class="form-group row">

            <label for="staticEmail" class="col-sm-2 col-form-label">联系人</label>
            <div class="col-sm-2">
                <input type="text" class="form-control-plaintext" readonly value="{{ host_obj.idc.phone }}">
            </div>

            <label for="staticEmail" class="col-sm-2 col-form-label">机房联系人姓名</label>
            <div class="col-sm-2">
                <input type="text" class="form-control-plaintext" readonly value="{{ host_obj.idc.name }}">
            </div>
            <label for="staticEmail" class="col-sm-2 col-form-label">邮箱</label>
            <div class="col-sm-2">
                <input type="text" class="form-control-plaintext" readonly value="{{ host_obj.idc.email }}">
            </div>

        </div>

        <div class="form-group row">

            <label for="staticEmail" class="col-sm-2 col-form-label">修改机房</label>

            <div class="col-sm-4">
                <select class="form-control" name="idc">
                    <option value="{{ host_obj.idc.id }}">{{ host_obj.idc.name }}</option>
                    {% for oneidc in idc %}
                        <option value="{{ oneidc.id }}">{{ oneidc.idc_name_all }}机房地址在{{ oneidc.address }}</option>
                    {% endfor %}
                </select>
            </div>

        </div>


        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">用户信息</h6>
        </div>

        <div class="form-group row">

            <label for="staticEmail" class="col-sm-2 col-form-label">账户</label>
            <div class="col-sm-2">
                <input type="text" class="form-control-plaintext" readonly value="{{ host_user }}">
            </div>

            <label for="staticEmail" class="col-sm-2 col-form-label">机房联系人姓名</label>
            <div class="col-sm-2">
                <input type="text" class="form-control-plaintext" readonly value="{{ host_obj.idc.name }}">
            </div>
            <label for="staticEmail" class="col-sm-2 col-form-label">邮箱</label>
            <div class="col-sm-2">
                <input type="text" class="form-control-plaintext" readonly value="{{ host_obj.idc.email }}">
            </div>

        </div>


    </form>



{% endblock %}